name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: msvc 2019 build
      run: |
       cd “C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\”
       .\MSBuild.exe $Env:GITHUB_WORKSPACE\Engine\Engine\Engine\Engine.vcxproj
